apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: public.ecr.aws/l4v6k6q7/609e6f97dc3bd7a240c3fc0587448b72_projects:latest
        ports:
        - containerPort: 80
        env:
        - name: PROJECTS_DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: users-database-connection-string
              key: database_url