apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: public.ecr.aws/l4v6k6q7/689289bfd7b0db6b706123cfa0b95825_users:latest
        ports:
        - containerPort: 80
        env:
        - name: USERS_DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: users-database-connection-string
              key: database_url
        - name: USERS_DATABASE_NAME
          value: users
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db