apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-mongo-storage-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /home/c/users_mongo